title: Joe Duffy's Blog
url: http://joeduffyblog.com
description: Adventures in the high-tech underbelly
email: joeduffy@acm.org

markdown: kramdown
excerpt_separator: "\n\n"

permalink: /:year/:month/:day/:title/
timezone: America/Los_Angeles

paginate: 10

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]
